# -*- coding: utf-8 -*-
"""text_summaraization_transformers.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hzEDOZ54kpxB5WfY2Q0EN47Gad7ngHiy
"""

# Install Required Libraries
!pip install -q transformers torch sentencepiece gradio pandas numpy scikit-learn fuzzywuzzy python-Levenshtein

import gradio as gr
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM
from fuzzywuzzy import fuzz
from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd
import numpy as np
import torch

# Load T5 Model
model_name = "t5-small"

tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSeq2SeqLM.from_pretrained(model_name)

def summarize_text(input_text):

    if not input_text.strip():
        return "Please enter some text.", "", ""

    original_words = len(input_text.split())

    target_words = max(30, int(original_words * 0.40))
    min_words = max(15, int(target_words * 0.5))

    text = "summarize: " + input_text

    inputs = tokenizer(
        text,
        max_length=512,
        truncation=True,
        return_tensors="pt"
    )

    summary_ids = model.generate(
        inputs["input_ids"],
        max_length=min(target_words, 150),
        min_length=min_words,
        num_beams=4,
        early_stopping=True
    )

    summary = tokenizer.decode(
        summary_ids[0],
        skip_special_tokens=True
    )

    similarity = fuzz.token_set_ratio(
        input_text,
        summary
    )

    compression_ratio = round(
        (len(summary.split()) / original_words) * 100,
        2
    )

    # Scikit-learn Vocabulary Analysis
    vectorizer = CountVectorizer(stop_words="english")
    vectorizer.fit([input_text])

    vocab_size = len(vectorizer.get_feature_names_out())

    stats = f"""
Original Words      : {original_words}
Summary Words       : {len(summary.split())}
Compression Ratio   : {compression_ratio}%
Similarity Score    : {similarity}%
Vocabulary Size     : {vocab_size}
"""

    return summary, stats, f"Similarity Score: {similarity}%"

# Gradio UI
with gr.Blocks(title="Text Summarization Dashboard") as demo:

    gr.Markdown("# 📝 Text Summarization Dashboard (T5-Small)")

    with gr.Row():

        input_text = gr.Textbox(
            label="Input Text",
            lines=20,
            placeholder="Paste your text here..."
        )

        output_summary = gr.Textbox(
            label="Summary Output",
            lines=20
        )

    summarize_btn = gr.Button("Summarize")

    stats_output = gr.Textbox(
        label="Statistics"
    )

    similarity_output = gr.Textbox(
        label="Accuracy Metric"
    )

    summarize_btn.click(
        summarize_text,
        inputs=input_text,
        outputs=[
            output_summary,
            stats_output,
            similarity_output
        ]
    )

demo.launch(share=True)